version: "3.8"

services:
  frontend:
    container_name: engteklif-frontend
    image: engteklif-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5050
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    container_name: engteklif-backend
    image: engteklif-backend
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/myapp
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=myapp

volumes:
  mongodb_data:
