version: "3.8"

services:
  frontend:
    container_name: engteklif-frontend
    image: engteklif-frontend
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://188.132.220.35:5051 # 5050 yerine 5051
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - engteklif-network # Network ekle

  backend:
    container_name: engteklif-backend
    image: engteklif-backend
    build: ./backend
    ports:
      - "5051:5050"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://engteklif-mongodb:27017/myapp # Container ismini değiştir
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - engteklif-mongodb # Dependency ismini değiştir
    networks:
      - engteklif-network # Network ekle

  engteklif-mongodb: # Container ismini değiştir
    image: mongo:5.0
    container_name: engteklif-mongodb # Açık container ismi ekle
    ports:
      - "27018:27017"
    volumes:
      - engteklif_mongodb_data:/data/db # Volume ismini değiştir
    environment:
      - MONGO_INITDB_DATABASE=myapp
    networks:
      - engteklif-network # Network ekle

networks:
  engteklif-network: # Yeni network tanımla
    driver: bridge

volumes:
  engteklif_mongodb_data: # Volume ismini değiştir
