import { createUseStyles } from "react-jss";

export const DashboardPageStyles = createUseStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: 0,
    width: '100%',
    height: 'auto',
    marginTop: 80,
    padding: '0px 100px',
    boxSizing: 'border-box',
    '@media (max-width:1000px)': {
      padding: '0px 12px',
    },
  },
  firstSection: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: 'calc(100vh - 80px)',
    boxSizing: 'border-box',
    rowGap: 32,
    alignItems: 'center',
    justifyContent: 'start',
    paddingTop: 32,
    '@media (max-width:1000px)': {
      rowGap: 24,
      paddingTop: 24,
    },
  },
  backgroundLogo: {
    height: 100,
    width: 'auto',
    '@media (max-width:1000px)': {
      width: 250,
      height: 'auto',
    },
  },
  title: {
    fontSize: 24,
    fontWeight: 600,
    color: '#181a25',
    textAlign: 'center',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 18,
    },
  },
  exp: {
    fontSize: "1rem",
    color: '#55565d',
    textAlign: 'center',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 12,
      width: '100%',
    },
    '& span': {
      fontStyle: 'italic',
    },
  },
  uploadSection: {
    width: '100%',
    height: 'auto',
    boxSizing: 'border-box',
    padding: 24,
    backgroundColor: 'white',
    borderRadius: 16,
    display: 'flex',
    flexDirection: 'column',
    rowGap: 16,
    '@media (max-width:1000px)': {
      padding: 16,
      borderRadius: 12,
      rowGap: 12,
    },
  },
  fileSelection: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    boxSizing: 'border-box',
    padding: 8,
    width: '100%',
    border: '1px solid #181a2520',
    borderRadius: 4,
    backgroundColor: '#181a2505',
  },
  fileSelectionButton: {
    border: 'none',
    backgroundColor: '#181a2520',
    color: '#181a25',
    padding: '4px 8px',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 14,
    transition: 'background 0.2s',
    '&:hover': {
      backgroundColor: '#181a2530',
    },
    '&:active': {
      backgroundColor: '#181a2540',
    },
    '@media (max-width:1000px)': {
      fontSize: 12,
    },
  },
  fileIcon: {
    height: 24,
    width: 24,
  },
  fileSelectionText: {
    fontSize: 14,
    fontWeight: 400,
    color: '#55565d',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 12,
    },
  },
  uploadButton: {
    border: 'none',
    backgroundColor: '#195cd7',
    color: 'white',
    width: '100%',
    boxSizing: 'border-box',
    padding: 12,
    borderRadius: 4,
    cursor: 'pointer',
    transition: 'background 0.2s',
    fontSize: 16,
    fontWeight: 500,
    '&:hover': {
      backgroundColor: '#1c67f0',
    },
    '&:active': {
      backgroundColor: '#174bb5',
    },
    '&:disabled': {
      backgroundColor: '#cccccc',
      cursor: 'not-allowed',
    },
    '@media (max-width:1000px)': {
      fontSize: 14,
    },
  },
  processingInfo: {
    fontSize: 14,
    fontWeight: 400,
    color: '#55565d',
    textAlign: 'center',
    margin: 0,
  },
  uploadedItem: {
    width: '100%',
    height: 'auto',
    borderRadius: 4,
    border: '1px solid #181a2520',
    display: 'flex',
    flexDirection: 'column',
    rowGap: 16,
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: 24,
    boxSizing: 'border-box',
    '@media (max-width:1000px)': {
      padding: 16,
      rowGap: 12,
    },
  },
  uploadedItemFirstSection: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  uploadedItemStatus: {
    display: 'flex',
    flexDirection: 'row',
    columnGap: 4,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2px 8px',
    borderRadius: 4,
    '&.green': {
      backgroundColor: '#179054',
    },
    '&.yellow': {
      backgroundColor: '#ffbf0a',
    },
    '&.red': {
      backgroundColor: '#dc3545',
    },
    '&.blue': {
      backgroundColor: '#195cd7',
    },
  },
  uploadedItemStatusIcon: {
    '& [class*="fa"]': {
      color: 'white',
    }
  },
  uploadedItemStatusText: {
    fontSize: 12,
    fontWeight: 500,
    color: 'white',
    margin: 0,
  },
  progressContainer: {
    width: '100%',
    backgroundColor: '#eef2f8',
    borderRadius: 999,
    height: 20,
    position: 'relative',
    overflow: 'hidden',
    '@media (max-width:1000px)': {
      height: 15,
    },
  },
  progressBar: {
    height: '100%',
    background: 'linear-gradient(to right, #9cc5ff, #195cd7)',
    borderRadius: 999,
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#181a25',
    fontSize: 12,
    fontWeight: 500,
    transition: 'width 0.3s ease',
  },
  progressText: {
    zIndex: 1,
    color: 'white',
    fontSize: 12,
    fontWeight: 500,
  },
  line: {
    width: '100%',
    height: 2,
    backgroundColor: '#181a2510',
    marginTop: 32,
    marginBottom: 32,
    boxSizing: 'border-box',
    '@media (max-width:1000px)': {
      marginTop: 24,
      marginBottom: 24,
    },
  },
  analyseSection: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: 32,
    alignItems: 'center',
    '@media (max-width:1000px)': {
      rowGap: 24,
    },
  },
  iconTextDiv: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    '@media (max-width:1000px)': {
      columnGap: 4,
    },
  },
  titleSmall: {
    fontSize: 18,
    color: '#181a25',
    fontWeight: 500,
    textAlign: 'center',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 15,
    },
  },
  analyseItem: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
    border: '1px solid #181a2520',
    display: 'flex',
    flexDirection: 'column',
    rowGap: 0,
    alignItems: 'flex-start',
    justifyContent: 'center',
    '&.active': {
      backgroundColor: '#195cd720',
    },
    '@media (max-width:1000px)': {
      padding: 0,
    },
  },
  analyseFirstSection: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: 24,
    boxSizing: 'border-box',
    cursor: 'pointer',
    '@media (max-width:1000px)': {
      padding: 16,
    },
  },
  analyseItemInsideDiv: {
    backgroundColor: 'white',
    display: 'flex',
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    rowGap: 16,
    boxSizing: 'border-box',
    padding: 16,
    overflow: 'auto',
    borderRadius: 4,
    '@media (max-width:1000px)': {
      padding: 12,
      rowGap: 12,
    },
  },
  analyseFirstDiv: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    columnGap: 32,
    width: '100%',
    '@media (max-width:1000px)': {
      flexDirection: 'column',
      justifyContent: 'flex-start',
      rowGap: 24,
    },
  },
  analyseAlias: {
    color: '#181a25',
    fontSize: 14,
    fontWeight: 600,
    backgroundColor: '#195cd710',
    padding: 12,
    borderRadius: 8,
    width: 'fit-content',
    margin: 0,
  },
  modelDiv: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: 16,
    alignItems: 'center',
  },
  modelSection: {
    width: 200,
    height: 200,
    backgroundColor: 'white',
    border: '1px solid #181a2520',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  modelImage: {
    width: '100%',
    height: 'auto',
    borderRadius: 8,
    objectFit: 'contain',
  },
  modelShowButton: {
    padding: '12px 48px',
    fontSize: 14,
    fontWeight: 500,
    color: '#195cd7',
    backgroundColor: '#195cd720',
    borderRadius: 8,
    transition: 'background 0.2s',
    cursor: 'pointer',
    border: 'none',
    '&:hover': {
      backgroundColor: '#195cd730',
    },
    '&:active': {
      backgroundColor: '#195cd740',
    },
  },
  analyseSubtitleDiv: {
    fontSize: 16,
    fontWeight: 500,
    color: '#181a25',
    padding: 16,
    backgroundColor: '#195cd710',
    borderRadius: 8,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    boxSizing: 'border-box',
    marginTop: 12,
    '@media (max-width:1000px)': {
      fontSize: 14,
      padding: 12,
    },
  },
  analyseInsideItem: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    alignItems: 'center',
    rowGap: 0,
    columnGap: 0,
    boxSizing: 'border-box',
    padding: '0 12px',
    '@media (max-width:1000px)': {
      gridTemplateColumns: '1fr 1fr',
      rowGap: 12,
      columnGap: 12,
    },
  },
  analyseItemTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#181a25',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 12,
    },
  },
  analyseItemExp: {
    fontSize: 14,
    fontWeight: 500,
    color: '#55565d',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 12,
    },
  },
  lineAnalyseItem: {
    width: '100%',
    height: 1,
    backgroundColor: '#181a2520',
  },
  analyseMaterialDiv: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr',
    alignItems: 'center',
    rowGap: 0,
    columnGap: 0,
    fontSize: 14,
    fontWeight: 500,
    color: '#181a25',
    padding: 16,
    backgroundColor: '#195cd710',
    borderRadius: 8,
    width: '100%',
    height: '100%',
    '@media (max-width:1000px)': {
      display: 'inline-grid',
      gridTemplateColumns: 'repeat(4, minmax(120px, 1fr))',
      overflowX: 'auto',
      minWidth: 'max-content',
    },
  },
  materialTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#181a25',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 12,
    },
  },
  analyseMaterialExpDiv: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr',
    alignItems: 'center',
    rowGap: 0,
    columnGap: 0,
    fontSize: 14,
    fontWeight: 500,
    color: '#181a25',
    padding: '0 16px',
    borderRadius: 8,
    width: '100%',
    height: '100%',
    '@media (max-width:1000px)': {
      display: 'inline-grid',
      gridTemplateColumns: 'repeat(4, minmax(120px, 1fr))',
      overflowX: 'auto',
      minWidth: 'max-content',
    },
  },
  materialExp: {
    fontSize: 14,
    fontWeight: 400,
    color: '#55565d',
    margin: 0,
    '@media (max-width:1000px)': {
      fontSize: 12,
    },
  },
  analyseButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 8,
    width: 300,
    height: 50,
    border: 'none',
    backgroundColor: '#10b86b',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    color: 'white',
    cursor: 'pointer',
    transition: 'background 0.2s',
    '&:hover': {
      backgroundColor: '#10ae66',
    },
    '&:active': {
      backgroundColor: '#15a161',
    },
    '@media (max-width:1000px)': {
      width: '100%',
      height: 40,
      fontSize: 12,
    },
  },
  excelButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 8,
    width: 300,
    height: 50,
    border: 'none',
    backgroundColor: '#ffbf0a',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    color: 'white',
    cursor: 'pointer',
    transition: 'background 0.2s',
    '&:hover': {
      backgroundColor: '#ffcd41',
    },
    '&:active': {
      backgroundColor: '#ffda73',
    },
    '@media (max-width:1000px)': {
      width: '100%',
      height: 40,
      fontSize: 12,
    },
  },
  hiddenFileInput: {
    display: 'none',
  },
  retryButton: {
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    padding: '8px 16px',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 12,
    '&:hover': {
      backgroundColor: '#c82333',
    },
  },
  loadingIcon: {
    animation: '$spin 1s linear infinite',
  },
  '@keyframes spin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
});